# This is a basic workflow to help you get started with Actions

name: Push pre-built Docker container GitHub Action

# Controls when the action will run. 
on:
  push:
    branches: [ master, py38, py39, py310 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Docker image and push to GitHub Packages
        uses: sphinx-toolbox/push-prebuilt-action@release-st
        with:
          push-branch: sphinx-3.3.1
          docker-registry: ghcr.io
          docker-repotag: ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker-user: x-access-token
          docker-token: ${{ github.token }}
